"""Add parent_id column with cascading delete to tasks

Revision ID: 239e63b2945f
Revises: da62985aba13
Create Date: 2024-05-20 21:23:20.724945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239e63b2945f'
down_revision = 'da62985aba13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tasks', ['parent_id'], ['task_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
