"""units

Revision ID: 3a9396b8f16d
Revises: d1544fb3b7ca
Create Date: 2024-06-03 18:13:29.849363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9396b8f16d'
down_revision = 'd1544fb3b7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=255), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('unit')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
