"""equipment productivity

Revision ID: 59a6d0abc4df
Revises: e37929a85c0c
Create Date: 2024-06-03 17:57:33.734761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a6d0abc4df'
down_revision = 'e37929a85c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('productivity', sa.Float(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('workload',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('workload',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('productivity')

    # ### end Alembic commands ###
