"""Add on delete cascade and table args

Revision ID: 5c4d5eb23813
Revises: 239e63b2945f
Create Date: 2024-05-25 11:53:31.649221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4d5eb23813'
down_revision = '239e63b2945f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_skills', schema=None) as batch_op:
        batch_op.drop_constraint('project_skills_project_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('project_skills_skill_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'skills', ['skill_id'], ['skill_id'], ondelete='CASCADE')

    with op.batch_alter_table('task_manpower', schema=None) as batch_op:
        batch_op.drop_constraint('task_manpower_task_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('task_manpower_manpower_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'manpower', ['manpower_id'], ['manpower_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['task_id'], ondelete='CASCADE')

    with op.batch_alter_table('task_skills', schema=None) as batch_op:
        batch_op.drop_constraint('task_skills_task_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('task_skills_skill_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'skills', ['skill_id'], ['skill_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['task_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('task_skills_skill_id_fkey', 'skills', ['skill_id'], ['skill_id'])
        batch_op.create_foreign_key('task_skills_task_id_fkey', 'tasks', ['task_id'], ['task_id'])

    with op.batch_alter_table('task_manpower', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('task_manpower_manpower_id_fkey', 'manpower', ['manpower_id'], ['manpower_id'])
        batch_op.create_foreign_key('task_manpower_task_id_fkey', 'tasks', ['task_id'], ['task_id'])

    with op.batch_alter_table('project_skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('project_skills_skill_id_fkey', 'skills', ['skill_id'], ['skill_id'])
        batch_op.create_foreign_key('project_skills_project_id_fkey', 'projects', ['project_id'], ['project_id'])

    # ### end Alembic commands ###
