"""Edit equip table drop cascade

Revision ID: 5feb7ec1de16
Revises: 7b9ed2d5e1b5
Create Date: 2024-05-05 11:44:13.510645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5feb7ec1de16'
down_revision = '7b9ed2d5e1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equip_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('availability')

    with op.batch_alter_table('task_equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equip_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('task_equipment_task_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['task_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'equipment', ['equip_id'], ['equip_id'], ondelete='CASCADE')
        batch_op.drop_column('equipment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('task_equipment_task_id_fkey', 'tasks', ['task_id'], ['task_id'])
        batch_op.drop_column('equip_id')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('equip_id')

    # ### end Alembic commands ###
