"""save project with task IDs

Revision ID: 9bc3f31a35d5
Revises: 5c4d5eb23813
Create Date: 2024-05-28 12:26:51.592448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc3f31a35d5'
down_revision = '5c4d5eb23813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_ids', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('task_ids')

    # ### end Alembic commands ###
