"""Updated tables

Revision ID: c31b18d9b3af
Revises: 9bc3f31a35d5
Create Date: 2024-06-02 21:03:52.071958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31b18d9b3af'
down_revision = '9bc3f31a35d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_workers', sa.Integer(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workload', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('productivity_rate', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('dependencies', sa.ARRAY(sa.Integer()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('dependencies')
        batch_op.drop_column('productivity_rate')
        batch_op.drop_column('workload')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('max_workers')

    # ### end Alembic commands ###
