"""Update units in tables

Revision ID: d1544fb3b7ca
Revises: 59a6d0abc4df
Create Date: 2024-06-03 18:10:48.245462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1544fb3b7ca'
down_revision = '59a6d0abc4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=255), nullable=False))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('unit')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
