"""Remove age, gender, location from manpower table

Revision ID: e2f1cf9834ca
Revises: 17878f7bcaa5
Create Date: 2024-05-01 17:26:36.638286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f1cf9834ca'
down_revision = '17878f7bcaa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manpower', schema=None) as batch_op:
        batch_op.drop_column('age')
        batch_op.drop_column('gender')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manpower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
