"""allocated_workers

Revision ID: e73e964353ce
Revises: 0fef9d736c6c
Create Date: 2024-06-05 05:10:25.901414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73e964353ce'
down_revision = '0fef9d736c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocated_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('num_workers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocated_workers')
    # ### end Alembic commands ###
