"""removed allocated workers table

Revision ID: fecaebaa402c
Revises: e73e964353ce
Create Date: 2024-06-09 16:40:17.390852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecaebaa402c'
down_revision = 'e73e964353ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocated_workers')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allocated_workers', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('allocated_workers')

    op.create_table('allocated_workers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_workers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], name='allocated_workers_skill_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name='allocated_workers_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='allocated_workers_pkey')
    )
    # ### end Alembic commands ###
